
platform:
  db:
    host: localhost
    port: 5432
    dbname: dna
    user: postgres
    password: dna2021

enhancer:
  log_level: info

event_uploader:
  batch_size: 100

path_uploader:
  min_path_count: 10
  batch_size: 10
  max_pending_sec: 5