
platform:
  db:
    host: localhost
    port: 5432
    dbname: dna
    user: postgres
    password: dna2021

tracker:
  # detector: yolov4
  model_file: dna/track/deepsort/ckpts/model640.pt
  min_detection_score: 0
  n_init: 3
  metric_threshold: 0.55
  max_iou_distance: 0.85
  max_overlap_ratio: 0.75
  max_age: 20
  min_size: [30, 20]
  det_mapping:
    car: car
    bus: bus
    truck: car
  log_level: DEBUG

enhancer:
  log_level: info

  event_uploader:
    batch_size: 100

  path_uploader:
    min_path_count: 10
    batch_size: 10
    max_pending_sec: 5