
platform:
  db:
    host: localhost
    port: 5432
    dbname: dna
    user: postgres
    password: dna2021

tracker:
  deep_sort:
    detector: yolov4
    model_file: dna/track/deepsort/ckpts/model640.pt
    # model_file: dna/track/deepsort/ckpts/vehicle_model280.pt
    n_init: 3
    matching_threshold: 0.55
    max_iou_distance: 0.7
    max_age: 10
    min_detection_score: 0
    det_mapping:
      car: car
      bus: bus
      truck: car

event_uploader:
  batch_size: 100

path_uploader:
  min_path_count: 20
  batch_size: 10
  max_pending_sec: 5